from screeninfo import get_monitors

# Screen size
for m in get_monitors():
    if m.is_primary:
        SCREEN_WIDTH = m.width
        SCREEN_HEIGHT = m.height
        
# Drawer
DRAWER_WIDTH = 200
DRAWER_LOGO_HEIGHT = 150
DRAWER_BUTTON_HEIGHT = 40
DRAWER_BUTTON_ICON_WIDTH = 30
DRAWER_BUTTON_ICON_HEIGHT = 30

# Projects tab
PROJECTS_TAB_PADDING_LEFT = 20
PROJECTS_TAB_PADDING_RIGHT = 20
PROJECTS_TAB_PADDING_TOP = 20
PROJECTS_TAB_PADDING_BOTTOM = 20

# Projects
PROJECTS_FRAME_WIDTH = SCREEN_WIDTH - DRAWER_WIDTH - PROJECTS_TAB_PADDING_LEFT - PROJECTS_TAB_PADDING_RIGHT
PROJECTS_NR_COLUMNS = 4
PROJECT_CARD_ASPECT_RATIO = 4 / 2
PROJECT_CARD_MARGIN = 20
PROJECT_CARD_WIDTH = (PROJECTS_FRAME_WIDTH - (PROJECTS_NR_COLUMNS - 1) * PROJECT_CARD_MARGIN) / PROJECTS_NR_COLUMNS
PROJECT_CARD_HEIGHT = PROJECT_CARD_WIDTH / PROJECT_CARD_ASPECT_RATIO
PROJECT_PLUS_ICON_HEIGHT = 40

# Models
MODELS_NR_COLUMNS = 4
MODEL_CARD_ASPECT_RATIO = 4 / 2
MODEL_CARD_MARGIN = 20
MODEL_CARD_WIDTH = (PROJECTS_FRAME_WIDTH - (MODELS_NR_COLUMNS - 1) * MODEL_CARD_MARGIN) / MODELS_NR_COLUMNS
MODEL_CARD_HEIGHT = MODEL_CARD_WIDTH / MODEL_CARD_ASPECT_RATIO
MODEL_PLUS_ICON_HEIGHT = 40

# Header
HEADER_PADDING_LEFT = 0
HEADER_PADDING_RIGHT = 0
HEADER_PADDING_TOP = 0
HEADER_PADDING_BOTTOM = 20

# Search bar
SEARCH_BAR_HEIGHT = 40
SEARCH_BAR_WIDTH = 500
SEARCH_ICON_WIDTH = 20
SEARCH_ICON_HEIGHT = 20

# Calibration tab buttons
CALIBRATION_TAB_BUTTON_WIDTH = 0.99 * PROJECTS_FRAME_WIDTH  / 5
CALIBRATION_TAB_BUTTON_HEIGHT = 40